# Passion Project: Soccer Player Filter Dashboard

### Step 1: Load and Read the Data

In [1]:
# Import libraries
import pandas as pd

# Path to CSV file
file_path = '/Users/mukikrishnan/Desktop/AKPsi Passion Project/FB Ref Passion Project Data Detailed (xG included) - Sheet1.csv'

# Load the CSV file into a DataFrame
df = pd.read_csv(file_path)

# Display the first few rows of the DataFrame
print(df.head())

  Unnamed: 0       Unnamed: 1 Unnamed: 2 Unnamed: 3 Unnamed: 4 Unnamed: 5  \
0         Rk           Player        Gls         xG        Tkl        Att
1          1       Harry Kane         36       30.6         13        664
2          2    Kylian Mbappé         27         21          4        965
3          3  Serhou Guirassy         26       20.3          6        749
4          4   Erling Haaland         25       26.8          6        357

  Unnamed: 6 Unnamed: 7 Unnamed: 8       Unnamed: 9  ... Standard.6  \
0     Season        Age     Nation             Team  ...         FK
1  2023-2024         30    eng ENG    Bayern Munich  ...          4
2  2023-2024         24     fr FRA        Paris S-G  ...          2
3  2023-2024         27     gn GUI        Stuttgart  ...          3
4  2023-2024         23     no NOR  Manchester City  ...          1

  Performance Performance.1 Performance.2 Performance.3 Performance.4  \
0         Gls           Ast           G+A          G-PK            PK
1          36             8            44            31             5
2          27             7            34            21             6
3          26             2            28            22             4
4          25             5            30            19             6

  Performance.5 Performance.6 Unnamed: 76 -additional
0         PKatt           PKm         Pos       -9999
1             5             0          FW    21a66f6a
2             8             2          FW    42fd9c7f
3             4             0          FW    923f4dda
4             7             1          FW    1f44ac21

[5 rows x 78 columns]

### Step 2: Data Cleaning

In [2]:
# Remove first row in order eliminate redundancy
new_column_names = df.iloc[0]
df = df[1:]
df.columns = new_column_names
df.reset_index(drop=True, inplace=True)
df.head()

,Rk,Player,Gls,xG,Tkl,Att,Season,Age,Nation,Team,...,FK,Gls,Ast,G+A,G-PK,PK,PKatt,PKm,Pos,-9999
0,1,Harry Kane,36,30.6,13,664,2023-2024,30,eng ENG,Bayern Munich,...,4,36,8,44,31,5,5,0,FW,21a66f6a
1,2,Kylian Mbappé,27,21,4,965,2023-2024,24,fr FRA,Paris S-G,...,2,27,7,34,21,6,8,2,FW,42fd9c7f
2,3,Serhou Guirassy,26,20.3,6,749,2023-2024,27,gn GUI,Stuttgart,...,3,26,2,28,22,4,4,0,FW,923f4dda
3,4,Erling Haaland,25,26.8,6,357,2023-2024,23,no NOR,Manchester City,...,1,25,5,30,19,6,7,1,FW,1f44ac21
4,5,Loïs Openda,24,22,3,508,2023-2024,23,be BEL,RB Leipzig,...,1,24,7,31,22,2,3,1,FW,8652a85c

In [3]:
print(df.columns)

Index(['Rk', 'Player', 'Gls', 'xG', 'Tkl', 'Att', 'Season', 'Age', 'Nation',
       'Team', 'Comp', 'MP', 'Min', '90s', 'Starts', 'Subs', 'unSub', 'Cmp',
       'Att', 'Cmp%', 'KP', '1/3', 'PPA', 'CrsPA', 'PrgP', 'TotDist',
       'PrgDist', 'Cmp', 'Att', 'Cmp%', 'Cmp', 'Att', 'Cmp%', 'Cmp', 'Att',
       'Cmp%', 'Tkl', 'TklW', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl', 'Att',
       'Tkl%', 'Lost', 'Blocks', 'Sh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',
       'xG', 'npxG', 'xAG', 'xG+xAG', 'xA', 'npxG+xAG', 'G-xG', 'np:G-xG',
       'A-xAG', 'npxG/Sh', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK',
       'Gls', 'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'PKm', 'Pos', '-9999'],
      dtype='object', name=0)

In [4]:
# List of columns to keep
columns_to_keep = [
    'Player', 'Season', 'Age', 'Nation', 'Team', 'Comp', 'MP', 'Min', 
    '90s', 'Starts', 'Subs', 'unSub', 'Gls', 'xG', 'Tkl', 'Att','Cmp',
    'Cmp%', 'KP', '1/3', 'PPA', 'CrsPA', 'PrgP', 'TotDist',
    'PrgDist', 'Cmp%', 'Cmp%', 'TklW', 'Def 3rd', 'Mid 3rd', 'Att 3rd',
    'Tkl%', 'Lost', 'Blocks', 'Sh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',
    'npxG', 'xAG', 'xG+xAG', 'xA', 'npxG+xAG', 'G-xG', 'np:G-xG',
    'A-xAG', 'npxG/Sh', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK',
    'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'PKm', 'Pos'
]

# Filter the DataFrame to keep only the specified columns
df_filtered = df[columns_to_keep]

# Find head of data set
df_filtered.head()

,Player,Season,Age,Nation,Team,Comp,MP,Min,90s,Starts,...,SoT%,Dist,FK,Ast,G+A,G-PK,PK,PKatt,PKm,Pos
0,Harry Kane,2023-2024,30,eng ENG,Bayern Munich,de Bundesliga,32,2839,31.5,32,...,43.3,14.4,4,8,44,31,5,5,0,FW
1,Kylian Mbappé,2023-2024,24,fr FRA,Paris S-G,fr Ligue 1,29,2158,24,24,...,44.6,18.3,2,7,34,21,6,8,2,FW
2,Serhou Guirassy,2023-2024,27,gn GUI,Stuttgart,de Bundesliga,27,2124,23.6,24,...,44.7,14.6,3,2,28,22,4,4,0,FW
3,Erling Haaland,2023-2024,23,no NOR,Manchester City,eng Premier League,29,2373,26.4,27,...,45.4,12,1,5,30,19,6,7,1,FW
4,Loïs Openda,2023-2024,23,be BEL,RB Leipzig,de Bundesliga,33,2607,29,32,...,50,14.1,1,7,31,22,2,3,1,FW

In [5]:
print(df_filtered.columns)

Index(['Player', 'Season', 'Age', 'Nation', 'Team', 'Comp', 'MP', 'Min', '90s',
       'Starts', 'Subs', 'unSub', 'Gls', 'Gls', 'xG', 'xG', 'Tkl', 'Tkl',
       'Tkl', 'Att', 'Att', 'Att', 'Att', 'Att', 'Att', 'Cmp', 'Cmp', 'Cmp',
       'Cmp', 'Cmp%', 'Cmp%', 'Cmp%', 'Cmp%', 'KP', '1/3', 'PPA', 'CrsPA',
       'PrgP', 'TotDist', 'PrgDist', 'Cmp%', 'Cmp%', 'Cmp%', 'Cmp%', 'Cmp%',
       'Cmp%', 'Cmp%', 'Cmp%', 'TklW', 'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl%',
       'Lost', 'Blocks', 'Sh', 'Sh', 'Pass', 'Int', 'Tkl+Int', 'Clr', 'Err',
       'npxG', 'xAG', 'xG+xAG', 'xA', 'npxG+xAG', 'G-xG', 'np:G-xG', 'A-xAG',
       'npxG/Sh', 'Sh', 'Sh', 'G/Sh', 'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK',
       'Ast', 'G+A', 'G-PK', 'PK', 'PKatt', 'PKm', 'Pos'],
      dtype='object', name=0)

In [6]:
# Remove duplicate columns within dataframe

# Columns to ensure are unique
columns_to_deduplicate = ["Gls", "xG", "Tkl", "Att"]

# Reverse the DataFrame to prioritize the last occurrence when dropping duplicates
df_reversed = df_filtered.iloc[:, ::-1]

# Drop duplicates but only among the specified columns
df_reversed = df_reversed.loc[:, ~df_reversed.columns.duplicated(keep='first')]

# Reverse the DataFrame back to the original order
new_df = df_reversed.iloc[:, ::-1]

# Display the first few rows of the new DataFrame
print(new_df.head())

0           Player     Season Age   Nation             Team  \
0       Harry Kane  2023-2024  30  eng ENG    Bayern Munich
1    Kylian Mbappé  2023-2024  24   fr FRA        Paris S-G
2  Serhou Guirassy  2023-2024  27   gn GUI        Stuttgart
3   Erling Haaland  2023-2024  23   no NOR  Manchester City
4      Loïs Openda  2023-2024  23   be BEL       RB Leipzig

0                Comp  MP   Min   90s Starts  ...  SoT%  Dist FK Ast G+A G-PK  \
0       de Bundesliga  32  2839  31.5     32  ...  43.3  14.4  4   8  44   31
1          fr Ligue 1  29  2158    24     24  ...  44.6  18.3  2   7  34   21
2       de Bundesliga  27  2124  23.6     24  ...  44.7  14.6  3   2  28   22
3  eng Premier League  29  2373  26.4     27  ...  45.4    12  1   5  30   19
4       de Bundesliga  33  2607    29     32  ...    50  14.1  1   7  31   22

0 PK PKatt PKm Pos
0  5     5   0  FW
1  6     8   2  FW
2  4     4   0  FW
3  6     7   1  FW
4  2     3   1  FW

[5 rows x 60 columns]

In [7]:
print(new_df.columns)

Index(['Player', 'Season', 'Age', 'Nation', 'Team', 'Comp', 'MP', 'Min', '90s',
       'Starts', 'Subs', 'unSub', 'Gls', 'xG', 'Tkl', 'Att', 'Cmp', 'KP',
       '1/3', 'PPA', 'CrsPA', 'PrgP', 'TotDist', 'PrgDist', 'Cmp%', 'TklW',
       'Def 3rd', 'Mid 3rd', 'Att 3rd', 'Tkl%', 'Lost', 'Blocks', 'Pass',
       'Int', 'Tkl+Int', 'Clr', 'Err', 'npxG', 'xAG', 'xG+xAG', 'xA',
       'npxG+xAG', 'G-xG', 'np:G-xG', 'A-xAG', 'npxG/Sh', 'Sh', 'G/Sh',
       'G/SoT', 'SoT', 'SoT%', 'Dist', 'FK', 'Ast', 'G+A', 'G-PK', 'PK',
       'PKatt', 'PKm', 'Pos'],
      dtype='object', name=0)

In [9]:
new_df.shape

(2000, 60)

### Step 3. Export the data

In [ ]:
# Export the sorted DataFrame to CSV
sorted_df.to_csv('/Users/mukikrishnan/Desktop/AKPsi Passion Project/Sorted_Data.csv', index=False)

: